// src/components/ColorLegend.tsx
import { CATEGORY_COLORS, COLOR } from "../services/colorcoding";
import "./ColorLegend.scss";

const ColorLegend = () => {
  const getBulletStyle = (entry) => {
    const style = {
      backgroundColor: entry.color,
      color: entry.color,
    };
    if (entry.color === COLOR["ams-wit"]) {
      style["borderColor"] = COLOR["ams-zwart"];
    }
    return style;
  };

  return (
    <div>
      <h4>Betekenis kleuren</h4>
      <div className="legend">
        {CATEGORY_COLORS.map((entry, index) => {
          return (
            <div key={index} className="legend-entry">
              <span style={getBulletStyle(entry)} className="legend-bullet">
                &#9634;
              </span>
              {entry.text}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default ColorLegend;

// src/components/ColorLegend.vue
<template>
  <div>
    <div>Betekenis kleuren:</div>
    <div v-for="entry in legend" :key="entry.color" class="legend-entry">
      <span :style="getBulletStyle(entry)" class="legend-bullet">&#9634;</span>
      {{entry.text}}
    </div>
  </div>
</template>

<script>
import { CATEGORY_COLORS, COLOR } from '../services/colorcoding'

export default {
  name: 'ColorLegend',
  components: {
  },
  props: [
  ],
  data () {
    return {
      legend: CATEGORY_COLORS
    }
  },
  computed: {
  },
  methods: {
    getBulletStyle (entry) {
      const style = {
        'background-color': entry.color,
        color: entry.color
      }
      if (entry.color === COLOR['ams-wit']) {
        style['border-color'] = COLOR['ams-zwart']
      }
      return style
    }
  },
  watch: {
  },
  created () {
  }
}

</script>

<style>
  .legend-entry {
    margin-top: 7px;
  }

  .legend-bullet {
    letter-spacing: 2px;
    border: 1px solid;
    margin-right: 7px;
  }
</style>
