// src/components/HorizontalBarChart.vue
<template>
  <div></div>
</template>

<script>
import vegaEmbed from 'vega-embed'
import vegaSpec from '../../static/charts/horizontalbar'
import { COLOR } from '../services/colorcoding'

const vegaEmbedOptions = {
  'actions': {
    'export': false,
    'source': false,
    'editor': false},
  'renderer': 'svg'
}

export default {
  props: [
    'chartdata'
  ],
  watch: {
    'chartdata' () {
      this.updateChart()
    }
  },
  methods: {
    updateChart () {
      vegaSpec.data.values = this.chartdata.map(d => ({
        key: d.label,
        value: d.recent.waarde || 0,
        label: d.recent.waarde === undefined ? 'Geen recente gegevens' : d.recent.waarde
      }))

      vegaSpec.layer[0].encoding.color.scale.range = this.chartdata
        .filter(d => d.recent.waarde)
        .map(d => d.recent.color || COLOR['ams-oranje'])

      vegaEmbed(this.$el, vegaSpec, vegaEmbedOptions)
    }
  },
  created () {
  },
  mounted () {
    this.updateChart()
  }
}
</script>

// src/components/HorizontalBarChart.jsx
import * as React from "react";
import vegaEmbed from "vega-embed";
import cloneDeep from "lodash/cloneDeep";

import vegaSpec from "../static/charts/horizontalbar.json";
import { COLOR } from "../services/colorcoding";
import util from "../services/util";
import "./HorizontalBarChart.scss";
import Icon from "./layout/Icon";

const vegaEmbedOptions = {
  actions: false,
  renderer: "svg",
};

const HorizontalBarChart = ({ title, icon, config, gwb }) => {
  const chartRef = React.useRef();

  async function updateData() {
    const chartdata = await util.getLatestConfigCijfers(gwb, config);
    const chartBase = cloneDeep(vegaSpec);

    chartBase.data.values = chartdata.map((d, i) => ({
      key: d.label,
      value: (d.recent && d.recent.waarde) || 0,
      label:
        d.recent && d.recent.waarde !== null
          ? d.recent.waarde
          : "Geen gegevens",
      color: (d.recent && d.recent.color) || COLOR["ams-oranje"],
      i,
    }));

    chartBase.layer[0].encoding.color.scale.range = chartBase.data.values.map(
      (v) => v.color
    );

    vegaEmbed(chartRef.current, chartBase, vegaEmbedOptions);
  }

  React.useEffect(() => {
    if (!gwb) {
      return;
    }

    updateData();
  }, [gwb]);

  return (
    <div className="block-container">
      {/* <tooltip cijfers="chartdata"> */}

      <Icon icon={icon} title={title} />
      <div ref={chartRef}></div>

      {/* </tooltip> */}
    </div>
  );
};

export default HorizontalBarChart;
