// src/components/LineChart.tsx
import { useEffect, useRef, useState } from "react";
import vegaEmbed from "vega-embed";
import cloneDeep from "lodash/cloneDeep";
import { Spinner } from "@amsterdam/asc-ui";

import util from "../services/util";

import { getColorsUsingStaticDefinition } from "../services/colorcoding";
import vegaSpec from "../static/charts/linechart";

const vegaEmbedOptions = {
  actions: false,
};

const LineChart = ({ title, gwb, config }) => {
  const chartRef = useRef<HTMLDivElement>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [showError, setShowError] = useState(false);

  async function updateData() {
    setIsLoading(true);
    setShowError(false);
    const colors = getColorsUsingStaticDefinition(config);
    const chartdata = await util.getConfigCijfers(gwb, config);
    const chartBase = cloneDeep(vegaSpec);

    const cijfers = chartdata
      .map((data) =>
        data.cijfers
          .filter((cijfer) => cijfer.waarde !== null)
          .map((cijfer) => ({
            x: cijfer.jaar,
            y: cijfer.waarde,
            variable: data.label,
            dash: /prognose/i.test(data.label), // show prognose variables as dashed lines
          })),
      )
      .flat();

    chartBase.data[0].values = cijfers;
    chartBase.scales[2].range = colors;

    if (chartRef.current && chartBase.data[0].values.length > 1) {
      setIsLoading(false);
      vegaEmbed(chartRef.current, chartBase, vegaEmbedOptions);
    } else {
      setIsLoading(false);
      setShowError(true);
    }
  }

  useEffect(() => {
    if (!gwb) {
      return;
    }

    updateData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gwb]);

  return (
    <div>
      <h5 className="text-center">{title}</h5>
      <div className="chart-container">
        {isLoading ? <Spinner /> : null}
        {showError && <p>Op dit schaalniveau is helaas geen informatie beschikbaar.</p>}
        <div ref={chartRef}></div>
      </div>
    </div>
  );
};

export default LineChart;

// src/components/LineChart.vue
<template>
  <div></div>
</template>

<script>
import { mapGetters } from 'vuex'
import util from '../services/util'
import vegaEmbed from 'vega-embed'
import vegaSpec from '../../static/charts/linechart5'
import { CHART_COLORS } from '../services/colorcoding'

const vegaEmbedOptions = {
  'actions': {
    'export': false,
    'source': false,
    'editor': false},
  'renderer': 'svg'
}

export default {
  name: 'LineChart',
  components: {
  },
  props: [
    'config'
  ],
  data () {
    return {
      chartdata: null
    }
  },
  computed: {
    ...mapGetters([
      'gwb'
    ])
  },
  methods: {
    async updateData () {
      this.chartdata = await util.getConfigCijfers(this.gwb, this.config)
      vegaSpec.data.values = []
      this.chartdata.forEach(data => {
        vegaSpec.data.values = vegaSpec.data.values.concat(
          data.cijfers.map(cijfer => ({
            x: cijfer.jaar,
            y: cijfer.waarde,
            variable: data.label
          }))
        )
      })
      vegaSpec.scales[2].range = CHART_COLORS
      vegaEmbed(this.$el, vegaSpec, vegaEmbedOptions)
    }
  },
  watch: {
    'gwb' () {
      this.updateData()
    }
  },
  created () {
    this.updateData()
  }
}

</script>

<style>
</style>
